# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 193853ddbef67c22a53e47a69d29ed4e5c2e0848ee12aed7c7bcf454856f56aeb615af960ca4e6a275294adfab94ab37e42be516ed442eeda6d0ab0e3688a244

test:
  secret_key_base: 672738d271f2fd6c4fbc973e09147a921182a4ae10950bd6d801111259ecc927963eb0a59631c80ae42f7f1f64564e941b1424eb3c95d1d65bd25ffb2c86c949

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
